# Generated by Django 3.2.7 on 2022-02-05 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_user_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='address',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
