# Generated by Django 3.2.7 on 2022-02-05 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0013_alter_listing_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data',
            name='value',
        ),
        migrations.AddField(
            model_name='data',
            name='create',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='data',
            name='leftover',
            field=models.IntegerField(default=0),
        ),
    ]
