# Generated by Django 3.2.7 on 2022-02-05 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0014_auto_20220205_1346'),
    ]

    operations = [
        migrations.RenameField(
            model_name='data',
            old_name='create',
            new_name='inventory',
        ),
    ]
