# Generated by Django 3.2.7 on 2022-02-06 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0015_rename_create_data_inventory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(choices=[('a', 'Asian Food'), ('b', 'European'), ('c', 'Gluten Free'), ('d Fat', 'Low Fat'), ('e', 'Keto'), ('f', 'Others')], default='Others', max_length=1000),
        ),
    ]
