# Generated by Django 3.2.7 on 2022-02-06 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0016_alter_listing_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data',
            name='inventory',
        ),
        migrations.AddField(
            model_name='data',
            name='create',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(choices=[('Asian', 'Asian'), ('European', 'European'), ('GlutenFree', 'Gluten Free'), ('Low Fat', 'Low Fat'), ('Keto', 'Keto'), ('Others', 'Others')], default='Others', max_length=1000),
        ),
    ]
