# Generated by Django 3.2.7 on 2022-02-06 01:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0017_auto_20220206_0118'),
    ]

    operations = [
        migrations.RenameField(
            model_name='data',
            old_name='create',
            new_name='inventory',
        ),
    ]
