# Generated by Django 3.2.7 on 2022-02-06 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0018_rename_create_data_inventory'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='sold',
            field=models.IntegerField(default=0),
        ),
    ]
